aliases:
    wip-workflow-clean: |-
        !gh api /repos/:owner/:repo/actions/workflows | jq -c '.workflows[] | select(.name | contains("WIP")) | .id' | while read i; do
            gh api -X GET /repos/:owner/:repo/actions/workflows/$i/runs?per_page=100 | jq '.workflow_runs[] | .id' | while read i; do
                gh api --silent -X DELETE /repos/:owner/:repo/actions/runs/$i
            done
        done
version: "1"
