github.com:
    oauth_token: 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
    user: zirdl
    git_protocol: https
    users:
        zirdl:
            oauth_token: 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
